{{- if .Values.ontap.mgmt.tls.caCertPath }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ontap-cosi-driver.fullname" . }}-ca-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ontap-cosi-driver.labels" . | nindent 4 }}
type: Opaque
stringData:
  ca.crt: |
{{ .Values.ontap.mgmt.tls.caCertContent | indent 4 }}
{{- end }}
