apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ontap-cosi-driver.fullname" . }}-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ontap-cosi-driver.labels" . | nindent 4 }}
type: Opaque
stringData:
  ONTAP_MGMT_ENDPOINT: {{ .Values.ontap.mgmt.endpoint | quote }}
  ONTAP_MGMT_SVM_UUID: {{ .Values.ontap.mgmt.svmUUID | quote }}
  ONTAP_MGMT_USE_SSL: {{ .Values.ontap.mgmt.ssl | toString | lower | quote }}
  ONTAP_MGMT_USERNAME: {{ .Values.ontap.mgmt.auth.username | quote }}
  ONTAP_MGMT_PASSWORD: {{ .Values.ontap.mgmt.auth.password | quote }}
  ONTAP_MGMT_CA_CERT_PATH: {{ .Values.ontap.mgmt.tls.caCertPath | quote }}
  ONTAP_MGMT_SKIP_TLS_VERIFY: {{ .Values.ontap.mgmt.tls.skipVerify | toString | lower | quote }}
  ONTAP_S3_ENDPOINT: {{ .Values.ontap.s3.endpoint | quote }}
  ONTAP_S3_REGION: {{ .Values.ontap.s3.region | quote }}
  ONTAP_S3_USE_SSL: {{ .Values.ontap.s3.ssl | toString | lower | quote }}
