apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ontap-cosi-driver.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "ontap-cosi-driver.labels" . | nindent 4 }}
